name: Cleanup Job

on:
  workflow_dispatch:   # allows manual trigger
  schedule:
    - cron: "0 */2 * * *" # every 2 hours

jobs:
  run-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Call cleanup API
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          set -euo pipefail
          curl -sS -f -L \
            -H "Authorization: Bearer $CRON_SECRET" \
            "https://file-share-jade.vercel.app/api/cleanup"

