name: Cleanup Job

on:
  workflow_dispatch:   # allows manual trigger
  schedule:
    - cron: "0 */2 * * *" # every 2 hours

jobs:
  run-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Call cleanup API
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            "https://file-share-jade.vercel.app/api/cleanup"

